import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {MongoMemoryServer} from 'mongodb-memory-server';
import mongoose from 'mongoose';
const mongo=await MongoMemoryServer.create();
process.env.MONGO_URI=mongo.getUri();
process.env.APP_SECRETS_KEY=Buffer.alloc(32,8).toString('base64');
delete process.env.OPENROUTER_API_KEY;delete process.env.DASHSCOPE_SINGAPORE_API_KEY;
const {transcribeRecording}=await import('../../lib/server/voice/transcription.js');
const {runConfiguredChat}=await import('../../lib/server/providers/directChat.js');
const {getModelConnection}=await import('../../lib/server/models/service.js');
const {default:User}=await import('../../models/User.js');
const {default:Transaction}=await import('../../models/CreditTransaction.js');
const {default:dbConnect}=await import('../../lib/db.js');
await dbConnect();
const recording={buffer:Buffer.from('fixture'),durationSeconds:10};
test.after(async()=>{await mongoose.disconnect();await mongo.stop();});
test('转写记录实际金额，同一操作不能重复向模型发送',async()=>{
 const user=await User.create({email:'voice@example.com',password:'hash'});
 const input={userId:String(user._id),recording,clientOperationId:randomUUID()};
 let calls=0;
 const runModel=async options=>{calls++;await options.onUpstreamRequest();options.onUsageRecord({usage:{input_tokens:100,output_tokens:50,cost:999}});return {text:'你好'};};
 const result=await transcribeRecording(input,{runModel});
 assert.equal(result.text,'你好');assert.equal(result.billing.status,'settled');assert.ok(Math.abs(result.billing.actualCostUsd-0.0002625)<1e-12);assert.ok(Math.abs(result.billing.actualCostCny-0.001764)<1e-12);
 const recorded=await Transaction.findOne({userId:user._id});assert.equal(recorded.actualCostCny,result.billing.actualCostCny);
 await assert.rejects(transcribeRecording(input,{runModel}),/重复/);assert.equal(calls,1);
});
test('没有积分账户也能转写，已发送但没有用量的请求记录为待核查',async()=>{
 const poor=await User.create({email:'poor@example.com',password:'hash'});
 let calls=0;
  const result=await transcribeRecording({userId:String(poor._id),recording,clientOperationId:randomUUID()},{runModel:async options=>{calls++;options.onUpstreamRequest();options.onUsageRecord({usage:{input_tokens:100,output_tokens:50}});return {text:'正常转写'};}});assert.equal(result.text,'正常转写');assert.equal(calls,1);
 const user=await User.create({email:'interrupted@example.com',password:'hash'});
 await assert.rejects(transcribeRecording({userId:String(user._id),recording,clientOperationId:randomUUID()},{runModel:async options=>{options.onUpstreamRequest();throw new Error('interrupted');}}),/interrupted/);
 const transaction=await Transaction.findOne({userId:user._id,feature:'voice_transcription'});
 assert.equal(transaction.status,'review_required');assert.equal(transaction.actualCostCny,null);
 assert.equal(transaction.actualCostUsd,null);
});
test('转写通过 Micu Gemini 原生 SSE 发送 WAV，并按含思考的 token 结算',async t=>{
 const key='MICU_GOOGLE_API_KEY';const saved=process.env[key];process.env[key]='transcription-secret';
 t.after(()=>{if(saved===undefined)delete process.env[key];else process.env[key]=saved;});
 const user=await User.create({email:'voice-micu@example.com',password:'hash'});
 let request;
 const fetchImpl=async(url,init)=>{
  request={url,headers:new Headers(init.headers),body:JSON.parse(init.body)};
  const event={responseId:'gemini-transcription',candidates:[{content:{parts:[{text:'逐字结果'}]},finishReason:'STOP'}],usageMetadata:{promptTokenCount:120,candidatesTokenCount:40,thoughtsTokenCount:10,cachedContentTokenCount:20,cost:999}};
  return new Response(`data: ${JSON.stringify(event)}\n\n`,{status:200,headers:{'content-type':'text/event-stream'}});
 };
 const runModel=async options=>runConfiguredChat({...options,fetchImpl},await getModelConnection(options.model));
 const result=await transcribeRecording({userId:String(user._id),recording,clientOperationId:randomUUID()},{runModel});
 assert.equal(result.text,'逐字结果');
 assert.equal(request.url,'https://www.micuapi.ai/v1beta/models/gemini-3.8-flash:streamGenerateContent?alt=sse');
 assert.equal(request.headers.get('x-goog-api-key'),'transcription-secret');
 assert.deepEqual(request.body.contents[0].parts[1],{inlineData:{mimeType:'audio/wav',data:'Zml4dHVyZQ=='}});
 assert.ok(Math.abs(result.billing.actualCostUsd-0.000264)<1e-12);
 assert.ok(Math.abs(result.billing.actualCostCny-0.00177408)<1e-12);
 const transaction=await Transaction.findOne({userId:user._id,feature:'voice_transcription'}).lean();
 assert.equal(transaction.usage.inputTokens,120);
 assert.equal(transaction.usage.cachedInputTokens,20);
 assert.equal(transaction.usage.outputTokens,50);
});
