import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {MongoMemoryServer} from 'mongodb-memory-server';
import mongoose from 'mongoose';
const mongo=await MongoMemoryServer.create();
process.env.MONGO_URI=mongo.getUri();
process.env.APP_SECRETS_KEY=Buffer.alloc(32,8).toString('base64');
delete process.env.OPENROUTER_API_KEY;delete process.env.DASHSCOPE_SINGAPORE_API_KEY;
const {saveProvider}=await import('../../lib/server/models/service.js');
const {saveTestedModel}=await import('./fixtures.mjs');
const {transcribeRecording}=await import('../../lib/server/voice/transcription.js');
const {default:User}=await import('../../models/User.js');
const {default:Transaction}=await import('../../models/CreditTransaction.js');
await saveProvider({id:'voice',name:'语音',protocol:'gemini',baseUrl:'https://1.1.1.1/v1beta',enabled:true,apiKey:'key'},{create:true});
await saveTestedModel({id:'voice-model',name:'语音',upstreamModel:'voice',providerId:'voice',group:'Google',enabled:true,isDefault:false,isTranscriptionDefault:true,sortOrder:0,contextWindow:100000,maxOutputTokens:2000,nativeInputs:['text','audio'],supportsTools:false,supportsWebSearch:false,pricing:{inputPerMillion:1,outputPerMillion:2,cachedInputPerMillion:1,cacheWritePerMillion:1},billingMode:'tokens',requestOptions:{}});
const recording={buffer:Buffer.from('fixture'),durationSeconds:10};
test.after(async()=>{await mongoose.disconnect();await mongo.stop();});
test('转写真实预留与结算积分，同一操作不能重复向模型发送',async()=>{
 const user=await User.create({email:'voice@example.com',password:'hash',creditBalance:100,creditsInitializedAt:new Date()});
 const input={userId:String(user._id),recording,clientOperationId:randomUUID()};
 let calls=0;
 const runModel=async options=>{calls++;await options.onUpstreamRequest();options.onUsageRecord({usage:{input_tokens:100,output_tokens:50}});return {text:'你好'};};
 const result=await transcribeRecording(input,{runModel});
 assert.equal(result.text,'你好');assert.equal(result.billing.status,'settled');assert.equal(result.billing.chargedPoints,1);
 const updated=await User.findById(user._id);assert.equal(updated.creditBalance,99);assert.equal(updated.creditHeld,0);
 await assert.rejects(transcribeRecording(input,{runModel}),/重复/);assert.equal(calls,1);
});
test('余额不足不会发出转写请求，已发送而无用量会保留冻结积分等待核查',async()=>{
 const poor=await User.create({email:'poor@example.com',password:'hash',creditBalance:0});
 let calls=0;
 await assert.rejects(transcribeRecording({userId:String(poor._id),recording,clientOperationId:randomUUID()},{runModel:async()=>{calls++;}}),error=>error.status===402);assert.equal(calls,0);
 const user=await User.create({email:'interrupted@example.com',password:'hash',creditBalance:100});
 await assert.rejects(transcribeRecording({userId:String(user._id),recording,clientOperationId:randomUUID()},{runModel:async options=>{options.onUpstreamRequest();throw new Error('interrupted');}}),/interrupted/);
 const transaction=await Transaction.findOne({userId:user._id,feature:'voice_transcription'});
 assert.equal(transaction.status,'review_required');assert.ok(transaction.reserved>0);
 assert.equal((await User.findById(user._id)).creditHeld,transaction.reserved);
});
test('任务支持管理员设置的小输出上限，并在上下文不足时拒绝预留积分',async()=>{
 const {getManagedModel}=await import('../../lib/server/models/service.js');
 const {createTaskBilling}=await import('../../lib/server/workbench/taskBilling.js');
 const model=await getManagedModel('voice-model');
 await saveTestedModel({...model,id:'short-model',contextWindow:512,maxOutputTokens:128,isTranscriptionDefault:false});
 const user=await User.create({email:'short@example.com',password:'hash',creditBalance:100});
 const task={_id:new mongoose.Types.ObjectId(),userId:user._id,model:'short-model',fingerprint:'short'};
 const billing=await createTaskBilling(task,new AbortController().signal);
 assert.equal(await billing.resolveMaxOutputTokens({pass:0,inputPayload:[{role:'user',content:'你好'}]}),128);
 assert.ok((await User.findById(user._id)).creditHeld>0);
 await billing.finalizeFailure();
 assert.equal((await User.findById(user._id)).creditHeld,0);
 await assert.rejects(billing.resolveMaxOutputTokens({pass:1,inputPayload:[{role:'user',content:'中文'.repeat(1000)}]}),/上下文/);
 assert.equal(await Transaction.countDocuments({userId:user._id}),1);
});
