import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {MongoMemoryServer} from 'mongodb-memory-server';
import mongoose from 'mongoose';
const mongo=await MongoMemoryServer.create();
process.env.MONGO_URI=mongo.getUri();
process.env.APP_SECRETS_KEY=Buffer.alloc(32,8).toString('base64');
delete process.env.OPENROUTER_API_KEY;delete process.env.DASHSCOPE_SINGAPORE_API_KEY;
const {transcribeRecording}=await import('../../lib/server/voice/transcription.js');
const {default:User}=await import('../../models/User.js');
const {default:Transaction}=await import('../../models/CreditTransaction.js');
const {default:dbConnect}=await import('../../lib/db.js');
await dbConnect();
const recording={buffer:Buffer.from('fixture'),durationSeconds:10};
test.after(async()=>{await mongoose.disconnect();await mongo.stop();});
test('转写记录实际金额，同一操作不能重复向模型发送',async()=>{
 const user=await User.create({email:'voice@example.com',password:'hash'});
 const input={userId:String(user._id),recording,clientOperationId:randomUUID()};
 let calls=0;
 const runModel=async options=>{calls++;await options.onUpstreamRequest();options.onUsageRecord({usage:{input_tokens:100,output_tokens:50,cost:0.0002}});return {text:'你好'};};
 const result=await transcribeRecording(input,{runModel});
 assert.equal(result.text,'你好');assert.equal(result.billing.status,'settled');assert.ok(result.billing.actualCostCny>0);assert.ok(Math.abs(result.billing.actualCostUsd-0.0002)<1e-12);
 const recorded=await Transaction.findOne({userId:user._id});assert.equal(recorded.actualCostCny,result.billing.actualCostCny);
 await assert.rejects(transcribeRecording(input,{runModel}),/重复/);assert.equal(calls,1);
});
test('没有积分账户也能转写，已发送但没有用量的请求记录为待核查',async()=>{
 const poor=await User.create({email:'poor@example.com',password:'hash'});
 let calls=0;
 const result=await transcribeRecording({userId:String(poor._id),recording,clientOperationId:randomUUID()},{runModel:async options=>{calls++;options.onUpstreamRequest();options.onUsageRecord({usage:{input_tokens:100,output_tokens:50,cost:0.0002}});return {text:'正常转写'};}});assert.equal(result.text,'正常转写');assert.equal(calls,1);
 const user=await User.create({email:'interrupted@example.com',password:'hash'});
 await assert.rejects(transcribeRecording({userId:String(user._id),recording,clientOperationId:randomUUID()},{runModel:async options=>{options.onUpstreamRequest();throw new Error('interrupted');}}),/interrupted/);
 const transaction=await Transaction.findOne({userId:user._id,feature:'voice_transcription'});
 assert.equal(transaction.status,'review_required');assert.equal(transaction.actualCostCny,null);
 assert.equal(transaction.actualCostUsd,null);
});
