'use client';
import { useEffect, useState } from 'react';
import { fieldClass, buttonClass } from '@/app/components/chat/ChatSettingsDialog';
const labels = { conversations: '对话', projects: '项目', files: '文件', skills: '技能', memories: '记忆', settings: '个人设置' };
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
const json = (method, body) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
export default function BackupsPanel() {
  const [selection, setSelection] = useState(Object.keys(labels)), [password, setPassword] = useState(''), [jobs, setJobs] = useState([]), [schedules, setSchedules] = useState([]), [connections, setConnections] = useState([]), [connectionId, setConnectionId] = useState(''), [destinationPath, setDestinationPath] = useState(''), [frequency, setFrequency] = useState('daily'), [time, setTime] = useState('02:00'), [weekday, setWeekday] = useState(0), [upload, setUpload] = useState(null), [restorePassword, setRestorePassword] = useState(''), [preview, setPreview] = useState(null), [applySettings, setApplySettings] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = async () => { const [history, plans] = await Promise.all([request('/api/backups'), request('/api/backups/schedules')]); setJobs(history.jobs); setSchedules(plans.schedules); };
  useEffect(() => { Promise.all([request('/api/backups'), request('/api/backups/schedules')]).then(([history, plans]) => { setJobs(history.jobs); setSchedules(plans.schedules); }).catch(e => setError(e.message)); request('/api/connections').then(data => setConnections(data.connections.filter(c => c.kind !== 'mcp' && c.enabled))).catch(e => setError(e.message)); }, []);
  const act = async fn => { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const config = () => ({ selection, password, ...(connectionId ? { destination: { connectionId, path: destinationPath } } : {}) });
  const restoreForm = () => { const body = new FormData(); body.append('file', upload); body.append('password', restorePassword); return body; };
  return <div className="space-y-6"><div><h3 className="font-semibold">备份与恢复</h3><p className="mt-1 text-sm text-zinc-500">备份使用你设置的密码加密。请妥善保管密码，遗失后无法恢复。</p></div>{error && <p role="alert" className="text-sm text-red-500">{error}</p>}{notice && <p role="status" className="text-sm text-emerald-600">{notice}</p>}
    <section className="space-y-3"><h4 className="font-medium text-sm">选择备份内容</h4><div className="flex flex-wrap gap-4">{Object.entries(labels).map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selection.includes(key)} onChange={e => setSelection(current => e.target.checked ? [...current, key] : current.filter(v => v !== key))} />{label}</label>)}</div><p className="text-xs text-zinc-500">不包含花费记录、登录状态、服务密钥、网页操作状态、连接密码和权限授权。头像需要同时勾选文件；配音偏好会保存，但不会重建服务商的自定义音色。</p><label className="block text-sm">备份密码<input aria-label="备份密码" type="password" autoComplete="new-password" className={`${fieldClass} mt-2`} minLength={10} maxLength={200} placeholder="至少 10 个字符" value={password} onChange={e => setPassword(e.target.value)} /></label>
      <label className="block text-sm">保存位置<select aria-label="备份保存位置" className={`${fieldClass} mt-2`} value={connectionId} onChange={e => setConnectionId(e.target.value)}><option value="">保存在此账户，可手动下载</option>{connections.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}</select></label>{connectionId && <label className="block text-sm">远端文件夹<input className={`${fieldClass} mt-2`} placeholder="例如 backups" value={destinationPath} onChange={e => setDestinationPath(e.target.value)} /></label>}
      <button disabled={busy || !selection.length || password.length < 10 || (Boolean(connectionId) && !destinationPath.trim())} className={buttonClass} onClick={() => act(async () => { await request('/api/backups', json('POST', config())); await load(); setNotice('加密备份已生成，可以在备份记录中下载。'); })}>{busy ? '正在处理…' : '立即备份'}</button>
    </section>
    <section className="space-y-3 border-t border-zinc-200 dark:border-zinc-700 pt-4"><h4 className="font-medium text-sm">定时备份</h4><p className="text-xs text-zinc-500">使用上面选择的内容、密码和保存位置。时间为北京时间；全站同时只运行一个备份或恢复任务。</p><div className="flex flex-wrap gap-2"><select aria-label="备份周期" className={`${fieldClass} !w-auto`} value={frequency} onChange={e => setFrequency(e.target.value)}><option value="daily">每天</option><option value="weekly">每周</option></select>{frequency === 'weekly' && <select aria-label="星期" className={`${fieldClass} !w-auto`} value={weekday} onChange={e => setWeekday(Number(e.target.value))}>{['日','一','二','三','四','五','六'].map((v,i) => <option key={i} value={i}>星期{v}</option>)}</select>}<input aria-label="备份时间" className={`${fieldClass} !w-auto`} type="time" value={time} onChange={e => setTime(e.target.value)} /><button disabled={busy || password.length < 10 || !selection.length} className={buttonClass} onClick={() => act(async () => { const [hour, minute] = time.split(':').map(Number); await request('/api/backups/schedules', json('POST', { ...config(), frequency, hour, minute, weekday })); await load(); setNotice('定时备份已保存。'); })}>添加定时备份</button></div>
      {schedules.map(schedule => <div key={schedule._id} className="rounded-xl border border-zinc-200 dark:border-zinc-700 p-3 space-y-2"><div className="flex justify-between items-center gap-2"><span className="text-sm">{schedule.frequency === 'daily' ? '每天' : `每周${['日','一','二','三','四','五','六'][schedule.weekday]}`} {String(schedule.hour).padStart(2,'0')}:{String(schedule.minute).padStart(2,'0')}</span><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={schedule.enabled} disabled={busy} onChange={e => act(async () => { await request(`/api/backups/schedules/${schedule._id}`, json('PATCH', { enabled: e.target.checked })); await load(); })} />启用</label><button className={buttonClass} disabled={busy} onClick={() => act(async () => { await request(`/api/backups/schedules/${schedule._id}`, { method: 'DELETE' }); await load(); })}>删除</button></div><p className="text-xs text-zinc-500">下次：{new Date(schedule.nextRunAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })} · {schedule.selection.map(s => labels[s]).join('、')}</p>{schedule.lastError && <p className="text-xs text-red-500">{schedule.lastError}</p>}</div>)}
    </section>
    <section className="space-y-3 border-t border-zinc-200 dark:border-zinc-700 pt-4"><h4 className="font-medium text-sm">从备份恢复</h4><label className="block text-sm">加密备份文件<input aria-label="加密备份文件" className={`${fieldClass} mt-2`} type="file" accept=".vxb" onChange={e => { setUpload(e.target.files[0] || null); setPreview(null); setApplySettings(false); }} /></label><label className="block text-sm">此备份的密码<input aria-label="恢复密码" className={`${fieldClass} mt-2`} type="password" autoComplete="off" value={restorePassword} onChange={e => { setRestorePassword(e.target.value); setPreview(null); }} /></label><button disabled={busy || !upload || restorePassword.length < 10} className={buttonClass} onClick={() => act(async () => setPreview(await request('/api/backups/inspect', { method: 'POST', body: restoreForm() })))}>检查备份内容</button>{preview && <div className="rounded-xl bg-zinc-50 dark:bg-zinc-800 p-4 space-y-3"><p className="text-sm">备份时间：{new Date(preview.createdAt).toLocaleString('zh-CN')}</p><p className="text-sm">{Object.entries(preview.counts).filter(([, count]) => count).map(([key,count]) => `${labels[key]} ${count}`).join(' · ')}</p><p className="text-xs text-zinc-500">{preview.restoreMode}</p>{preview.includesSettings && <label className="flex gap-2 text-sm"><input type="checkbox" checked={applySettings} onChange={e => setApplySettings(e.target.checked)} />应用备份中的个人设置</label>}<button disabled={busy} className={buttonClass} onClick={() => act(async () => { const body = restoreForm(); body.append('digest', preview.digest); body.append('applySettings', String(applySettings)); await request('/api/backups/restore', { method: 'POST', body }); setPreview(null); await load(); setNotice('恢复完成，原有内容已保留。'); })}>确认恢复为新副本</button></div>}</section>
    <section className="space-y-3 border-t border-zinc-200 dark:border-zinc-700 pt-4"><div className="flex items-center justify-between"><h4 className="font-medium text-sm">备份与恢复记录</h4><button disabled={busy} className={buttonClass} onClick={() => act(load)}>刷新</button></div>{jobs.length === 0 && <p className="text-sm text-zinc-500">还没有备份记录。</p>}{jobs.map(job => <div key={job._id} className="rounded-xl border border-zinc-200 dark:border-zinc-700 p-3"><div className="flex items-center flex-wrap gap-2"><p className="flex-1 text-sm">{job.type === 'restore' ? '恢复' : '备份'} · {new Date(job.createdAt).toLocaleString('zh-CN')}<span className="block text-xs text-zinc-500 mt-1">{{ running: '进行中', completed: '已完成', failed: '失败' }[job.status]}</span></p>{job.type === 'backup' && job.status === 'completed' && <a className={buttonClass} href={`/api/backups/${job._id}/download`}>下载</a>}<button disabled={busy || job.status === 'running'} className={buttonClass} onClick={() => act(async () => { await request(`/api/backups/${job._id}`, { method: 'DELETE' }); await load(); })}>删除记录</button></div>{job.error && <p className="mt-2 text-xs text-red-500">{job.error}</p>}</div>)}</section>
  </div>;
}
