'use client';
import {useEffect,useRef,useState} from 'react';
const button='rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 text-sm disabled:opacity-50';
export default function BrowserPanel(){
 const [status,setStatus]=useState({tabs:[]}),[view,setView]=useState(null),[url,setUrl]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[fileId,setFileId]=useState(''),[selected,setSelected]=useState(''),[downloadFile,setDownloadFile]=useState(null),[library,setLibrary]=useState([]);const image=useRef(null);
 const load=async()=>{const r=await fetch('/api/browser');const data=await r.json();if(r.ok)setStatus(data);};
 useEffect(()=>{let alive=true;fetch('/api/browser').then(r=>r.json()).then(data=>{if(alive)setStatus(data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 const action=async value=>{setBusy(true);setError('');try{const r=await fetch('/api/browser/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tabId:view?.tabId,...value})});const data=await r.json();if(!r.ok)throw new Error(data.error);if(value.action==='close_tab')setView(null);if(data.screenshot)setView(data);if(data.file)setDownloadFile(data.file);await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const close=async revoke=>{setBusy(true);try{const r=await fetch(`/api/browser?revoke=${revoke}`,{method:'DELETE'});const data=await r.json();if(!r.ok)throw new Error(data.error);setView(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <div className="space-y-4"><h3 className="text-lg font-semibold">浏览器</h3><p className="text-sm text-slate-500">在这里直接登录网站、输入验证码或处理验证。点击画面选择位置，再输入文字。登录状态仅保存在你的账户中；同时最多打开三个页面。</p>{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}{status.busy&&<p className="text-sm text-amber-600">浏览器正忙，任务会排队等待。</p>}
 <form className="flex gap-2" onSubmit={e=>{e.preventDefault();action({action:'navigate',url});}}><input aria-label="网址" placeholder="输入 https:// 开头的网址" className="min-w-0 flex-1 rounded-lg border bg-transparent px-3 py-2 text-sm" value={url} onChange={e=>setUrl(e.target.value)}/><button className={button} disabled={busy||status.busy}>打开</button><button className={button} type="button" disabled={busy||status.busy} onClick={()=>action({action:'new_tab',url})}>新页面</button></form>
 <div className="flex flex-wrap gap-2">{status.tabs.map(tab=><button key={tab.id} disabled={busy} className={`${button} max-w-52 truncate ${view?.tabId===tab.id?'bg-slate-100 dark:bg-slate-800':''}`} onClick={()=>action({action:'observe',tabId:tab.id})}>{tab.url==='about:blank'?'空白页面':tab.url}</button>)}</div>
 {status.active&&<p className="text-xs text-slate-500">{status.manual?'你正在操作浏览器':'浏览器已交给任务使用'}</p>}{status.active&&<div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>action({action:'takeover'})}>手动接管</button><button disabled={busy} className={button} onClick={()=>action({action:'resume'})}>交还给任务</button><button disabled={busy} className={button} onClick={()=>action({action:'observe'})}>刷新画面</button><button disabled={busy} className={button} onClick={()=>action({action:'close_tab'})}>关闭当前页面</button></div>}
 {view?.screenshot&&<div className="space-y-3"><p className="text-xs text-slate-500 break-all">{view.title} · {view.url}</p>
{/* eslint-disable-next-line @next/next/no-img-element */}
<img ref={image} src={view.screenshot} alt="可操作的浏览器页面" className={`w-full rounded-lg border ${busy?'opacity-60':'cursor-crosshair'}`} onClick={e=>{if(busy)return;const rect=image.current.getBoundingClientRect();action({action:'click',x:(e.clientX-rect.left)*1080/rect.width,y:(e.clientY-rect.top)*760/rect.height});}}/>
 <div className="flex gap-2"><input type="password" autoComplete="off" aria-label="输入到网页的文字或密码" placeholder="输入文字、密码或验证码" className="min-w-0 flex-1 rounded-lg border bg-transparent px-3 py-2 text-sm" value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy||!text} className={button} onClick={()=>{action({action:'type',text});setText('');}}>键入</button><button disabled={busy} className={button} onClick={()=>action({action:'key',key:'Enter'})}>回车</button></div>
 <div className="flex flex-wrap gap-2">{[['Tab','下一个输入框'],['Backspace','退格'],['Escape','退出弹层']].map(([key,label])=><button disabled={busy} key={key} className={button} onClick={()=>action({action:'key',key})}>{label}</button>)}<button disabled={busy} className={button} onClick={()=>action({action:'scroll',amount:-600})}>向上滚动</button><button disabled={busy} className={button} onClick={()=>action({action:'scroll',amount:600})}>向下滚动</button></div>
 <details onToggle={e=>{if(e.currentTarget.open)fetch('/api/library').then(r=>r.json()).then(data=>setLibrary(data.files||[])).catch(e=>setError(e.message));}}><summary className="cursor-pointer text-sm">网页文件上传与下载</summary><div className="space-y-2 mt-2"><select aria-label="网页元素" className="w-full rounded-lg border bg-transparent p-2 text-sm" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择网页中的文件框或下载按钮</option>{view.elements?.map(el=><option value={el.element} key={el.element}>{el.element} · {el.label||el.text||el.placeholder||el.type||'未命名元素'}</option>)}</select><select aria-label="选择要上传的文件" className="w-full rounded-lg border bg-transparent p-2 text-sm" value={fileId} onChange={e=>setFileId(e.target.value)}><option value="">从文件库选择文件</option>{library.map(file=><option key={file.fileId} value={file.fileId}>{file.name}</option>)}</select><div className="flex gap-2"><button disabled={busy||selected===''||!fileId} className={button} onClick={()=>action({action:'upload',element:Number(selected),fileId})}>上传选定文件</button><button disabled={busy||selected===''} className={button} onClick={()=>action({action:'download',element:Number(selected)})}>点击并接收下载</button></div></div></details></div>}
 {downloadFile&&<a className="inline-block text-sm text-blue-600 underline" href={downloadFile.url} download={downloadFile.name}>下载：{downloadFile.name}</a>}<div className="flex gap-2 border-t pt-4"><button disabled={busy} className={button} onClick={()=>close(false)}>关闭浏览器并保存登录</button><button disabled={busy} className={`${button} text-red-500`} onClick={()=>close(true)}>退出并删除登录状态</button></div></div>;
}
