'use client';
import {useEffect,useState} from 'react';
const field='w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm';
const button='rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 text-sm disabled:opacity-50';
async function request(url,method='GET',body){const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error || '操作失败');return data;}
export default function ConnectionsPanel(){
 const [connections,setConnections]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState({name:'',kind:'mcp',url:'',root:'',authType:'apiKey',apiKey:'',username:'',password:'',accessKeyId:'',secretAccessKey:'',knownHosts:'',region:'',apiKeyHeader:'Authorization',clientId:'',clientSecret:''}),[importText,setImportText]=useState(''),[files,setFiles]=useState(null),[preview,setPreview]=useState(''),[library,setLibrary]=useState([]),[writeFileId,setWriteFileId]=useState(''),[destination,setDestination]=useState(''),[writeConfirmed,setWriteConfirmed]=useState(false),[oauthLinks,setOauthLinks]=useState({});
 const load=async()=>setConnections((await request('/api/connections')).connections);
 useEffect(()=>{let alive=true;request('/api/connections').then(data=>{if(alive)setConnections(data.connections);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 const run=async fn=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const edit=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const browse=async(id,path='')=>{const data=await request(`/api/connections/${id}/files?path=${encodeURIComponent(path)}`);setFiles({id,path,items:data.files});setPreview('');setDestination(path?path+'/':'');setWriteConfirmed(false);setLibrary((await request('/api/library')).files);};
 return <div className="space-y-5"><div><h3 className="text-lg font-semibold">外部工具与远端文件</h3><p className="mt-1 text-sm text-slate-500">接入自己的工具和文件夹。密钥仅用于你的连接；工具需逐个开启，写入外部系统前会请你确认。</p></div>{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}
 <div className="space-y-3 rounded-xl border border-slate-200 dark:border-slate-700 p-4"><h4 className="font-medium">添加连接</h4><div className="grid gap-3 sm:grid-cols-2"><input className={field} placeholder="连接名称" value={draft.name} onChange={e=>edit('name',e.target.value)}/><select className={field} value={draft.kind} onChange={e=>edit('kind',e.target.value)}>{[['mcp','MCP 工具'],['webdav','WebDAV'],['s3','S3 对象存储'],['sftp','SFTP'],['smb','SMB'],['ftp','FTP（加密连接）']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><input className={field} placeholder={draft.kind==='mcp'?'https://example.com/mcp':'公开访问地址，例如 https://files.example.com'} value={draft.url} onChange={e=>edit('url',e.target.value)}/>
 {draft.kind==='mcp'?<><select className={field} value={draft.authType} onChange={e=>edit('authType',e.target.value)}><option value="apiKey">API 密钥</option><option value="oauth">网页登录授权（OAuth）</option><option value="none">无需认证</option></select>{draft.authType==='apiKey'&&<><select className={field} value={draft.apiKeyHeader} onChange={e=>edit('apiKeyHeader',e.target.value)}><option value="Authorization">Bearer 密钥</option><option value="X-API-Key">X-API-Key 密钥</option></select><input className={field} type="password" autoComplete="new-password" placeholder="API 密钥" value={draft.apiKey} onChange={e=>edit('apiKey',e.target.value)}/></>}{draft.authType==='oauth'&&<details><summary className="text-sm cursor-pointer">填写服务商提供的客户端信息（如需要）</summary><input className={`${field} mt-2`} placeholder="Client ID" value={draft.clientId} onChange={e=>edit('clientId',e.target.value)}/><input className={`${field} mt-2`} type="password" placeholder="Client Secret（如需要）" value={draft.clientSecret} onChange={e=>edit('clientSecret',e.target.value)}/></details>}</>:<><input className={field} placeholder="限定文件夹（S3 请填写 bucket/文件夹）" value={draft.root} onChange={e=>edit('root',e.target.value)}/>{draft.kind==='s3'?<div className="grid gap-3"><input className={field} placeholder="Access Key ID" value={draft.accessKeyId} onChange={e=>edit('accessKeyId',e.target.value)}/><input className={field} type="password" placeholder="Secret Access Key" value={draft.secretAccessKey} onChange={e=>edit('secretAccessKey',e.target.value)}/><input className={field} placeholder="区域" value={draft.region} onChange={e=>edit('region',e.target.value)}/></div>:<div className="grid gap-3 sm:grid-cols-2"><input className={field} autoComplete="off" placeholder="用户名" value={draft.username} onChange={e=>edit('username',e.target.value)}/><input className={field} type="password" autoComplete="new-password" placeholder="密码" value={draft.password} onChange={e=>edit('password',e.target.value)}/></div>}{draft.kind==='sftp'&&<textarea className={field} placeholder="服务器 known_hosts 公钥记录" value={draft.knownHosts} onChange={e=>edit('knownHosts',e.target.value)}/>}</>}
 <button disabled={busy} className={button} onClick={()=>run(async()=>{await request('/api/connections','POST',{name:draft.name,kind:draft.kind,config:{url:draft.url,root:draft.root,region:draft.region,authType:draft.authType,apiKeyHeader:draft.apiKeyHeader},credentials:{apiKey:draft.apiKey,username:draft.username,password:draft.password,accessKeyId:draft.accessKeyId,secretAccessKey:draft.secretAccessKey,knownHosts:draft.knownHosts,...(draft.clientId?{clientInformation:{client_id:draft.clientId,...(draft.clientSecret?{client_secret:draft.clientSecret}:{})}}:{})}});setDraft(d=>({...d,apiKey:'',password:'',secretAccessKey:'',clientSecret:''}));})}>添加连接</button>
 <details><summary className="cursor-pointer text-sm">从 MCP 配置导入</summary><textarea className={`${field} mt-3 min-h-28`} placeholder={'{"mcpServers":{"我的工具":{"url":"https://example.com/mcp"}}}'} value={importText} onChange={e=>setImportText(e.target.value)}/><button disabled={busy} className={`${button} mt-2`} onClick={()=>run(async()=>{await request('/api/connections','POST',{import:JSON.parse(importText)});setImportText('');})}>导入配置</button></details></div>
 {connections.map(c=><div key={c.id} className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3"><div className="flex items-center justify-between gap-3"><div><h4 className="font-medium">{c.name}</h4><p className="text-xs text-slate-500 break-all">{c.config.url}</p></div><label className="text-sm flex gap-2"><input type="checkbox" checked={c.enabled} disabled={busy} onChange={e=>run(()=>request(`/api/connections/${c.id}`,'PATCH',{enabled:e.target.checked}))}/>启用</label></div><div className="flex flex-wrap gap-2">{c.config.authType==='oauth'&&<button className={button} disabled={busy} onClick={()=>run(async()=>{const result=await request(`/api/connections/${c.id}/oauth`,'POST');if(result.authorizationUrl)setOauthLinks(links=>({...links,[c.id]:result.authorizationUrl}));})}>网页登录授权</button>}{oauthLinks[c.id]&&<a href={oauthLinks[c.id]} target="_blank" rel="noopener noreferrer" className={`${button} text-blue-600`}>前往授权页面</a>}<button className={button} disabled={busy} onClick={()=>run(async()=>{await request(`/api/connections/${c.id}/test`,'POST');})}>测试连接</button>{c.kind!=='mcp'&&<button className={button} disabled={busy} onClick={()=>run(()=>browse(c.id))}>浏览文件</button>}<button className={`${button} text-red-500`} disabled={busy} onClick={()=>run(()=>request(`/api/connections/${c.id}`,'DELETE'))}>删除</button></div>{c.testedAt&&<p className="text-xs text-emerald-600">已测试 · {new Date(c.testedAt).toLocaleString()}</p>}{c.tools?.map(tool=><label key={tool.name} className="flex gap-3 text-sm border-t border-slate-100 dark:border-slate-800 pt-2"><input type="checkbox" disabled={busy} checked={tool.enabled===true} onChange={e=>run(()=>request(`/api/connections/${c.id}`,'PATCH',{tools:[{name:tool.name,enabled:e.target.checked}]}))}/><span><span className="font-medium">{tool.title||tool.name}</span><span className="block text-xs text-slate-500">{tool.description}</span></span></label>)}{Boolean(c.resources?.length||c.prompts?.length)&&<p className="text-xs text-slate-500">{c.resources.length} 份资料 · {c.prompts.length} 个提示模板</p>}</div>)}
 {files&&<div className="rounded-xl border p-4 space-y-2"><div className="flex justify-between"><h4 className="font-medium">/{files.path}</h4><button className={button} onClick={()=>setFiles(null)}>关闭</button></div>{files.path&&<button className={button} onClick={()=>run(()=>browse(files.id,files.path.split('/').slice(0,-1).join('/')))}>上一级</button>}{files.items.map(item=><div className="flex flex-wrap items-center gap-2 py-1" key={item.path}><span className="flex-1 text-sm break-all">{item.isDirectory?'📁':'📄'} {item.name}</span>{item.isDirectory?<button className={button} onClick={()=>run(()=>browse(files.id,item.path))}>打开</button>:<><button className={button} onClick={()=>run(async()=>setPreview((await request(`/api/connections/${files.id}/files?read=true&path=${encodeURIComponent(item.path)}`)).text))}>查看文本</button><button className={button} onClick={()=>run(async()=>{const result=await request(`/api/connections/${files.id}/files`,'POST',{action:'import',path:item.path});setPreview(`已导入：${result.file.name}`);})}>导入</button></>}</div>)}<details className="border-t pt-3"><summary className="text-sm cursor-pointer">将文件写回远端</summary><div className="space-y-2 mt-2"><select className={field} aria-label="选择要写回的文件" value={writeFileId} onChange={e=>{setWriteFileId(e.target.value);setWriteConfirmed(false);}}><option value="">从文件库选择文件</option>{library.map(file=><option key={file.fileId} value={file.fileId}>{file.name}</option>)}</select><input className={field} placeholder="远端完整文件路径" value={destination} onChange={e=>{setDestination(e.target.value);setWriteConfirmed(false);}}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={writeConfirmed} onChange={e=>setWriteConfirmed(e.target.checked)}/>我确认写入此路径，并覆盖同名文件</label><button className={button} disabled={busy||!writeConfirmed||!writeFileId||!destination} onClick={()=>run(async()=>{await request(`/api/connections/${files.id}/files`,'POST',{action:'write',fileId:writeFileId,destinationPath:destination,confirmed:true});await browse(files.id,files.path);setPreview('文件已写回远端');})}>确认写回</button></div></details>{preview&&<pre className="whitespace-pre-wrap max-h-64 overflow-auto rounded-lg bg-slate-100 dark:bg-slate-900 p-3 text-xs">{preview}</pre>}</div>}
 </div>;
}
