'use client';
import { useEffect, useState } from 'react';
import { fieldClass, buttonClass } from '@/app/components/chat/ChatSettingsDialog';
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
const json = (method, body) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
export default function FilesPanel() {
  const [data, setData] = useState({ files: [], folders: [] }), [folderId, setFolderId] = useState(''), [selected, setSelected] = useState([]), [folderName, setFolderName] = useState(''), [editing, setEditing] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [moveTo, setMoveTo] = useState(''), [projects, setProjects] = useState([]), [projectId, setProjectId] = useState('');
  const load = async () => { setData(await request(`/api/library?folderId=${folderId}`)); setSelected([]); };
  useEffect(() => { request(`/api/library?folderId=${folderId}`).then(value => { setData(value); setSelected([]); }).catch(e => setError(e.message)); }, [folderId]);
  useEffect(() => { request('/api/projects').then(value => setProjects(value.projects)).catch(e => setError(e.message)); }, []);
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const download = () => act(async () => { const response = await fetch('/api/library/download', json('POST', { fileIds: selected })); if (!response.ok) throw new Error((await response.json()).error); const url = URL.createObjectURL(await response.blob()), a = document.createElement('a'); a.href = url; a.download = 'files.zip'; a.click(); URL.revokeObjectURL(url); });
  return <div className="space-y-5"><div><h3 className="font-semibold">个人文件库</h3><p className="text-sm text-zinc-500 mt-1">集中整理你的附件和生成文件，可复制到不同项目使用。</p></div>{error && <p role="alert" className="text-sm text-red-500">{error}</p>}
    <label className="block text-sm space-y-2"><span>当前文件夹</span><select aria-label="当前文件夹" className={fieldClass} value={folderId} onChange={e => setFolderId(e.target.value)}><option value="">全部根目录文件</option>{data.folders.map(f => <option key={f._id} value={f._id}>{f.name}</option>)}</select></label>
    <form className="flex gap-2" onSubmit={e => { e.preventDefault(); act(async () => { await request('/api/library/folders', json('POST', { name: folderName, parentId: folderId || null })); setFolderName(''); await load(); }); }}><input aria-label="新文件夹名称" className={fieldClass} value={folderName} onChange={e => setFolderName(e.target.value)} placeholder="新文件夹名称" /><button disabled={busy || !folderName.trim()} className={buttonClass}>新建文件夹</button></form>
    {folderId && <div className="flex flex-wrap items-center gap-2"><button disabled={busy || !folderName.trim()} className={buttonClass} onClick={() => act(async () => { await request(`/api/library/folders/${folderId}`, json('PATCH', { name: folderName })); setFolderName(''); await load(); })}>重命名当前文件夹</button><button disabled={busy} className={`${buttonClass} text-red-500`} onClick={() => act(async () => { await request(`/api/library/folders/${folderId}`, { method: 'DELETE' }); setFolderId(''); })}>删除当前文件夹及内容</button></div>}
    <label className={buttonClass}>批量上传<input aria-label="批量上传文件" type="file" multiple className="hidden" disabled={busy} onChange={e => { const uploads = [...e.target.files]; e.target.value = ''; act(async () => { const body = new FormData(); for (const file of uploads) body.append('files', file); if (folderId) body.append('folderId', folderId); await request('/api/library/upload', { method: 'POST', body }); await load(); }); }} /></label>
    <div className="space-y-2">{data.folders.filter(f => (f.parentId || '') === folderId).map(f => <button key={f._id} className={`${buttonClass} mr-2`} onClick={() => setFolderId(f._id)}>📁 {f.name}</button>)}{data.files.map(file => <div key={file.fileId} className="flex items-center gap-3 rounded-xl border border-zinc-200 dark:border-zinc-700 p-3"><input aria-label={`选择 ${file.name}`} type="checkbox" checked={selected.includes(file.fileId)} onChange={e => setSelected(current => e.target.checked ? [...current, file.fileId] : current.filter(id => id !== file.fileId))} /><div className="min-w-0 flex-1"><a href={file.url} download className="block truncate text-sm">{file.name}</a><span className="text-xs text-zinc-500">{(file.size / 1024).toFixed(1)} KB · {file.ownerType === 'library' ? '个人文件' : file.ownerType === 'project' ? '项目文件' : '对话与生成文件'}</span></div><button className={buttonClass} onClick={() => act(async () => { const result = await request(`/api/library/files/${file.fileId}${file.editable && file.size <= 200000 ? '?text=1' : ''}`); setEditing({ ...result.file, content: result.content }); })}>编辑</button></div>)}{!data.files.length && <p className="text-sm text-zinc-500">这里还没有文件。</p>}</div>
    {selected.length > 0 && <div className="space-y-3 rounded-xl bg-zinc-50 dark:bg-zinc-800 p-3"><p className="text-sm">已选择 {selected.length} 个文件</p><div className="flex gap-2"><button disabled={busy} className={buttonClass} onClick={download}>批量下载</button><button disabled={busy} className={`${buttonClass} text-red-500`} onClick={() => act(async () => { for (const id of selected) await request(`/api/library/files/${id}`, { method: 'DELETE' }); await load(); })}>删除所选</button></div><div className="flex gap-2"><select aria-label="移动目标文件夹" className={fieldClass} value={moveTo} onChange={e => setMoveTo(e.target.value)}><option value="">根目录</option>{data.folders.map(f => <option key={f._id} value={f._id}>{f.name}</option>)}</select><button disabled={busy} className={buttonClass} onClick={() => act(async () => { for (const id of selected) await request(`/api/library/files/${id}`, json('PATCH', { folderId: moveTo || null })); await load(); })}>移动文件</button></div><div className="flex gap-2"><select aria-label="复制目标项目" className={fieldClass} value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">选择项目</option>{projects.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select><button disabled={busy || !projectId} className={buttonClass} onClick={() => act(async () => { for (const id of selected) await request(`/api/library/files/${id}/copy`, json('POST', { projectId })); await load(); })}>复制到项目</button></div></div>}
    {folderId && <div className="flex gap-2"><select aria-label="文件夹移动目标" className={fieldClass} value={moveTo} onChange={e => setMoveTo(e.target.value)}><option value="">根目录</option>{data.folders.filter(f => f._id !== folderId).map(f => <option key={f._id} value={f._id}>{f.name}</option>)}</select><button disabled={busy || moveTo === folderId} className={buttonClass} onClick={() => act(async () => { await request(`/api/library/folders/${folderId}`, json('PATCH', { parentId: moveTo || null })); await load(); })}>移动当前文件夹</button></div>}
    {editing && <form className="space-y-3 border-t border-zinc-200 dark:border-zinc-700 pt-4" onSubmit={e => { e.preventDefault(); act(async () => { await request(`/api/library/files/${editing.fileId}`, json('PATCH', { name: editing.name, ...(editing.content !== undefined ? { content: editing.content } : {}) })); setEditing(null); await load(); }); }}><label className="block text-sm">文件名称<input className={`${fieldClass} mt-2`} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></label>{editing.content !== undefined && <label className="block text-sm">文本内容<textarea className={`${fieldClass} mt-2 font-mono`} rows={12} value={editing.content} onChange={e => setEditing({ ...editing, content: e.target.value })} /></label>}<div className="flex gap-2"><button className={buttonClass} disabled={busy}>保存</button><button type="button" className={buttonClass} onClick={() => setEditing(null)}>取消</button></div></form>}
  </div>;
}
