'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { fieldClass, buttonClass } from '@/app/components/chat/ChatSettingsDialog';
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
const json = (method, body) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
export default function SkillsPanel({ conversationId = null }) {
  const [skills, setSkills] = useState([]), [selected, setSelected] = useState(null), [content, setContent] = useState(''), [assets, setAssets] = useState([]), [asset, setAsset] = useState(null), [githubUrl, setGithubUrl] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [disabledIds, setDisabledIds] = useState([]);
  const load = async () => { setSkills((await request('/api/skills')).skills); if (conversationId) setDisabledIds((await request(`/api/conversations/${conversationId}/capabilities`)).disabledSkillIds || []); };
  useEffect(() => { request('/api/skills').then(data => setSkills(data.skills)).catch(e => setError(e.message)); if (conversationId) request(`/api/conversations/${conversationId}/capabilities`).then(data => setDisabledIds(data.disabledSkillIds || [])).catch(e => setError(e.message)); }, [conversationId]);
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const open = async id => { const data = await request(`/api/skills/${id}`); setSelected(data.skill); setContent(data.skill.content); setAssets(data.assets); setAsset(null); };
  const importFile = file => act(async () => { const body = new FormData(); body.append('file', file); const data = await request('/api/skills/import', { method: 'POST', body }); await load(); await open(data.skill._id); });
  return <div className="space-y-5">
    <div><h3 className="font-semibold">技能库</h3><p className="mt-1 text-sm text-zinc-500">管理助手的工作方法、参考资料和模板。脚本可以保存、阅读和导出，无法运行。</p></div>
    {error && <p role="alert" className="text-sm text-red-500">{error}</p>}
    <div className="flex flex-wrap gap-2"><button className={buttonClass} onClick={() => { setSelected({ _id: null, name: '新技能' }); setContent('---\nname: 新技能\ndescription: 技能的用途\n---\n\n在这里编写工作步骤。'); setAssets([]); setAsset(null); }}>新建技能</button><label className={buttonClass}>导入文件<input aria-label="导入技能文件" className="hidden" type="file" accept=".md,.zip,.skill" disabled={busy} onChange={e => { if (e.target.files[0]) importFile(e.target.files[0]); e.target.value = ''; }} /></label></div>
    <form className="flex gap-2" onSubmit={e => { e.preventDefault(); act(async () => { const data = await request('/api/skills/import', json('POST', { githubUrl })); await load(); await open(data.skill._id); }); }}><input aria-label="公开 GitHub 技能地址" className={fieldClass} placeholder="公开 GitHub 仓库或技能目录链接" value={githubUrl} onChange={e => setGithubUrl(e.target.value)} /><button disabled={busy || !githubUrl} className={buttonClass}>导入</button></form>
    <div className="space-y-2">{skills.map(skill => <div key={skill._id} className="rounded-xl border border-zinc-200 dark:border-zinc-700 p-3"><div className="flex items-center gap-3"><button className="flex-1 text-left" onClick={() => act(() => open(skill._id))}><span className="font-medium text-sm">{skill.name}</span><span className="block text-xs text-zinc-500 mt-1">{skill.description}</span></button><label className="flex gap-2 text-xs"><input type="checkbox" checked={skill.enabled} disabled={busy} onChange={e => act(async () => { await request(`/api/skills/${skill._id}`, json('PATCH', { enabled: e.target.checked })); await load(); })} />全局启用</label>{conversationId && <label className="flex gap-2 text-xs"><input type="checkbox" disabled={busy || !skill.enabled} checked={!disabledIds.includes(skill._id)} onChange={e => act(async () => { const ids = e.target.checked ? disabledIds.filter(id => id !== skill._id) : [...disabledIds, skill._id]; await request(`/api/conversations/${conversationId}/capabilities`, json('PUT', { disabledSkillIds: ids })); setDisabledIds(ids); })} />此对话启用</label>}</div></div>)}</div>
    {selected && <section className="border-t border-zinc-200 dark:border-zinc-700 pt-4 space-y-3"><div className="flex justify-between items-center"><h4 className="font-medium">{selected.name}</h4><button className={buttonClass} onClick={() => setSelected(null)}>收起</button></div>
      <div className="flex flex-wrap gap-2"><button className={buttonClass} onClick={() => { setAsset(null); setContent(selected.content || content); }}>SKILL.md</button>{assets.map(item => <button key={item.path} className={buttonClass} onClick={() => act(async () => { if (/\.(png|jpg|jpeg|webp|gif)$/i.test(item.path)) { setAsset({ ...item, previewUrl: `/api/skills/${selected._id}/assets?preview=1&path=${encodeURIComponent(item.path)}` }); return; } const response = await fetch(`/api/skills/${selected._id}/assets?path=${encodeURIComponent(item.path)}`); if (!response.ok) throw new Error('附件读取失败'); if (item.size > 200000 || !/\.(md|txt|json|ya?ml|csv|xml|html|css|js|ts|py|sh|mjs|cjs|bash|ps1)$/i.test(item.path)) { const url = URL.createObjectURL(await response.blob()); const a = document.createElement('a'); a.href = url; a.download = item.path.split('/').pop(); a.click(); URL.revokeObjectURL(url); return; } setAsset(item); setContent(await response.text()); })}>{item.path}{item.executable ? ' · 仅保存' : ''}</button>)}</div>
      {asset?.previewUrl ? <Image src={asset.previewUrl} alt={asset.path} width={800} height={500} unoptimized className="max-h-96 w-full object-contain rounded-xl bg-zinc-50 dark:bg-zinc-800" /> : <label className="block text-sm">{asset ? asset.path : '技能内容'}<textarea aria-label="技能内容" className={`${fieldClass} mt-2 font-mono`} rows={14} value={content} onChange={e => setContent(e.target.value)} /></label>}
      <div className="flex flex-wrap gap-2"><button disabled={busy || Boolean(asset?.previewUrl)} className={buttonClass} onClick={() => act(async () => { if (asset) await request(`/api/skills/${selected._id}/assets`, json('PUT', { path: asset.path, content })); else { const data = await request(selected._id ? `/api/skills/${selected._id}` : '/api/skills', json(selected._id ? 'PATCH' : 'POST', { content })); await open(data.skill._id); } await load(); })}>保存</button>{selected._id && <><a className={buttonClass} href={`/api/skills/${selected._id}/export`}>导出技能包</a>{selected.source?.type === 'github' && <button disabled={busy} className={buttonClass} onClick={() => act(async () => { await request(`/api/skills/${selected._id}/update-source`, { method: 'POST' }); await load(); await open(selected._id); })}>从 GitHub 更新</button>}<button disabled={busy} className={`${buttonClass} text-red-500`} onClick={() => act(async () => { await request(`/api/skills/${selected._id}`, { method: 'DELETE' }); setSelected(null); await load(); })}>删除技能</button></>}</div>
      {selected.source?.url && <p className="break-all text-xs text-zinc-500">来源：{selected.source.url}</p>}
      {selected.metadata && <details className="text-xs text-zinc-500"><summary>查看技能属性</summary><pre className="whitespace-pre-wrap mt-2">{JSON.stringify(selected.metadata, null, 2)}</pre></details>}
    </section>}
  </div>;
}
