'use client';
import { useEffect, useState } from 'react';
import { fieldClass, buttonClass } from '@/app/components/chat/ChatSettingsDialog';
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
const money = value => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY', minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(value);
const bytes = value => value >= 1073741824 ? `${(value/1073741824).toFixed(2)} GB` : value >= 1048576 ? `${(value/1048576).toFixed(1)} MB` : `${(value/1024).toFixed(1)} KB`;
const statusLabels = { queued: '等待中', running: '执行中', waiting_media: '正在生成素材', waiting_approval: '等待你的确认', completed: '已完成', failed: '失败', stopped: '已停止', interrupted: '已中断' };
const openAiPricedImageModels = new Set(['gpt-image-2.5-sunburst', 'gpt-image-2.5-flare']);
const eventLabels = {
  started: '任务开始', completed: '任务完成', failed: '任务失败', stopped: '任务已停止', interrupted: '任务已中断',
  model: '分析资料', billing: '记录花费', memory: '保存记忆', sources: '整理来源', artifact: '保存成果',
  context: '整理任务进度', tool_start: '开始执行步骤', tool_result: '步骤执行结果',
  media_submit: '开始生成素材', media_wait: '等待素材生成', approval_required: '等待你的确认',
};
const toolLabels = {
  list_documents: '查看项目资料', read_document: '阅读项目资料', list_library: '查看文件库',
  read_file: '读取文件', edit_file: '编辑文件', load_skill: '读取技能', read_skill_file: '阅读技能资料',
  read_skill_image: '查看技能图片', read_memory: '读取记忆', save_memory: '保存记忆',
  search_web: '联网搜索', read_webpage: '阅读网页', create_report: '生成报告', create_table: '生成表格',
  inspect_table: '查看表格', transform_table: '整理表格', read_task_step: '查看先前步骤', save_progress: '保存任务进度',
  media_capabilities: '查看媒体工具', list_media: '查看素材', generate_image: '生成图片', edit_image: '编辑图片', generate_speech: '生成语音',
  enhance_video: '增强视频画质', browser: '操作网页',
};
function eventLabel(event) {
  if (!event.tool) return eventLabels[event.type];
  if (event.tool.startsWith('ext_')) return '使用外部连接';
  return toolLabels[event.tool];
}
export default function UsagePanel() {
  const [month, setMonth] = useState(() => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit' }).format(new Date())), [model, setModel] = useState(''), [taskId, setTaskId] = useState(''), [data, setData] = useState(null), [events, setEvents] = useState([]), [storage, setStorage] = useState(null), [selected, setSelected] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const query = new URLSearchParams({ month, ...(model ? { model } : {}), ...(taskId ? { taskId } : {}) }).toString();
  useEffect(() => { Promise.all([request('/api/usage'), request('/api/usage/logs'), request('/api/usage/storage')]).then(([usage, logs, files]) => { setData(usage); setEvents(logs.events); setStorage(files); }).catch(e => setError(e.message)); }, []);
  const act = async fn => { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const load = async () => { const [usage, logs] = await Promise.all([request(`/api/usage?${query}`), request(`/api/usage/logs?${query}`)]); setData(usage); setEvents(logs.events); };
  return <div className="space-y-6"><div><h3 className="font-semibold">用量、记录与存储</h3><p className="text-sm text-zinc-500 mt-1">查看人民币花费、历史账单、任务执行记录和文件占用。每月 1 日按北京时间重新累计，历史记录会保留。</p></div>{error && <p role="alert" className="text-sm text-red-500">{error}</p>}{notice && <p role="status" className="text-sm text-emerald-600">{notice}</p>}
    <form className="space-y-3" onSubmit={e => { e.preventDefault(); act(load); }}><label className="block text-sm">账单月份<input aria-label="账单月份" className={`${fieldClass} mt-2`} type="month" required value={month} onChange={e => setMonth(e.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">模型<input aria-label="筛选模型" className={`${fieldClass} mt-2`} value={model} placeholder="全部模型" onChange={e => setModel(e.target.value)} /></label><label className="text-sm">任务编号<input aria-label="筛选任务" className={`${fieldClass} mt-2`} value={taskId} placeholder="全部任务" onChange={e => setTaskId(e.target.value)} /></label></div><button disabled={busy} className={buttonClass}>查询</button></form>
    {data && <><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-zinc-50 dark:bg-zinc-800 p-4"><p className="text-xs text-zinc-500">本月花费 · {data.currentMonth.month}</p><p className="text-2xl font-semibold mt-2">{money(data.currentMonth.costCny)}</p></div><div className="rounded-xl bg-zinc-50 dark:bg-zinc-800 p-4"><p className="text-xs text-zinc-500">所选范围花费</p><p className="text-2xl font-semibold mt-2">{money(data.summary.costCny)}</p></div><div className="rounded-xl bg-zinc-50 dark:bg-zinc-800 p-4"><p className="text-xs text-zinc-500">已记录调用</p><p className="text-2xl font-semibold mt-2">{data.summary.requests.toLocaleString()}</p></div></div>
      {data.currentMonth.unpricedRequests > 0 && <p className="text-xs text-amber-600">本月另有 {data.currentMonth.unpricedRequests} 次调用尚无费用数据，未计入本月金额。</p>}
      {data.summary.unpricedRequests > 0 && <p className="text-xs text-amber-600">所选范围有 {data.summary.unpricedRequests} 次调用尚无费用数据，未计入金额。</p>}
      <details open><summary className="text-sm font-medium cursor-pointer">历史月度花费</summary><div className="mt-3 space-y-2">{data.monthly.map(item => <button type="button" key={item._id} onClick={() => { setMonth(item._id); setModel(''); setTaskId(''); act(async () => { const [usage, logs] = await Promise.all([request(`/api/usage?month=${item._id}`), request(`/api/usage/logs?month=${item._id}`)]); setData(usage); setEvents(logs.events); }); }} className="flex w-full justify-between gap-3 rounded-lg p-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"><span>{item._id}</span><span>{money(item.costCny)} · {item.requests} 次{item.unpricedRequests > 0 ? ` · ${item.unpricedRequests} 次费用待记录` : ''}</span></button>)}{!data.monthly.length && <p className="text-sm text-zinc-500">暂无历史花费。</p>}</div></details>
      <details open><summary className="text-sm font-medium cursor-pointer">按模型统计</summary><div className="mt-3 space-y-2">{data.models.map(item => <div key={item._id} className="flex justify-between text-sm gap-3"><span className="break-all">{item._id}{openAiPricedImageModels.has(item._id) && <span className="ml-2 inline-block rounded bg-zinc-100 px-2 py-0.5 text-xs text-zinc-500 dark:bg-zinc-800">按 OpenAI 价格计算</span>}</span><span className="whitespace-nowrap">{money(item.costCny)} · {item.requests} 次</span></div>)}{data.models.some(item => openAiPricedImageModels.has(item._id)) && <p className="text-xs text-zinc-500">标注模型的费用按 OpenAI 官方价格和实际用量计算，可能与 Micu 的实际扣费不同。</p>}{!data.models.length && <p className="text-sm text-zinc-500">所选范围内没有用量记录。</p>}</div></details>
      <details><summary className="text-sm font-medium cursor-pointer">每日花费</summary><div className="mt-3 space-y-2">{data.daily.map(item => <div key={item._id} className="flex justify-between text-sm"><span>{item._id}</span><span>{money(item.costCny)} · {item.requests} 次</span></div>)}</div></details>
      <details><summary className="text-sm font-medium cursor-pointer">任务花费（最多 200 条）</summary><div className="mt-3 space-y-3">{data.tasks.map(task => <button key={task._id} className="block w-full text-left rounded-xl border border-zinc-200 dark:border-zinc-700 p-3" onClick={() => setTaskId(task._id)}><span className="text-sm">{task.model} · {statusLabels[task.status]} · {money(task.costCny)}</span><span className="block mt-1 text-xs text-zinc-500">{task._id} · {new Date(task.createdAt).toLocaleString('zh-CN')}</span></button>)}</div></details></>}
    <section className="border-t border-zinc-200 dark:border-zinc-700 pt-4 space-y-3"><div className="flex items-center justify-between"><h4 className="font-medium text-sm">工具执行记录</h4><a className={buttonClass} href={`/api/usage/diagnostics?${query}`}>下载诊断记录</a></div><p className="text-xs text-zinc-500">查看每一步的执行状态、耗时和失败原因。</p><div className="max-h-64 overflow-y-auto space-y-2">{events.map(event => <div key={event.id} className="text-xs border-b border-zinc-100 dark:border-zinc-800 pb-2"><div className="flex justify-between gap-2"><span>{eventLabel(event)}{event.status ? ` · ${{ ...statusLabels, done: '成功', settled: '已记账', review_required: '费用待核查', pending: '等待处理', reserved: '等待结算', settling: '正在结算', released: '未计费', rejected: '已取消计费' }[event.status]}` : ''}</span><span className="text-zinc-500 whitespace-nowrap">{new Date(event.createdAt).toLocaleString('zh-CN')}</span></div>{event.failureReason && <p className="mt-1 text-red-500">{event.failureReason}</p>}{event.code && <p className="mt-1 text-zinc-500">{event.code}</p>}{event.durationMs !== undefined && <span className="text-zinc-500">耗时 {event.durationMs} 毫秒</span>}</div>)}{!events.length && <p className="text-sm text-zinc-500">没有执行记录。</p>}</div></section>
    {storage && <section className="border-t border-zinc-200 dark:border-zinc-700 pt-4 space-y-3"><h4 className="font-medium text-sm">存储空间 · 共 {bytes(storage.totalBytes)}</h4><div className="space-y-2">{[...storage.categories, { category: 'skills', ...storage.skillAssets }, { category: 'backups', ...storage.backups }].map(item => <div key={item.category} className="flex justify-between text-sm"><span>{{ image: '图片', audio: '音频', video: '视频', document: '文档', skills: '技能附件', backups: '加密备份' }[item.category]} · {item.count} 个</span><span>{bytes(item.bytes)}</span></div>)}</div><p className="text-xs text-zinc-500">以下文件未用于对话、任务或头像，可选择清理。项目文件不在清理范围内。</p><div className="max-h-52 overflow-y-auto space-y-2">{storage.cleanupCandidates.map(file => <label key={file.fileId} className="flex gap-2 items-center text-sm"><input type="checkbox" checked={selected.includes(file.fileId)} onChange={e => setSelected(current => e.target.checked ? [...current, file.fileId] : current.filter(id => id !== file.fileId))} /><span className="flex-1 truncate">{file.name}</span><span className="text-xs text-zinc-500">{bytes(file.size)}</span></label>)}{!storage.cleanupCandidates.length && <p className="text-sm text-zinc-500">没有可清理的文件。</p>}</div><button disabled={busy || !selected.length} className={`${buttonClass} text-red-500`} onClick={() => act(async () => { const result = await request('/api/usage/storage', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileIds: selected }) }); setStorage(await request('/api/usage/storage')); setSelected([]); setNotice(`已清理 ${result.deleted} 个文件，释放 ${bytes(result.bytes)}。`); })}>清理选中的 {selected.length} 个文件</button></section>}
  </div>;
}
