'use client';
import {useEffect,useState} from 'react';
export default function TaskApprovals({taskId,onChanged}){
 const [items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{if(!taskId)return;let alive=true;const load=async()=>{try{const r=await fetch(`/api/tasks/${taskId}/approvals`);const data=await r.json();if(alive&&r.ok)setItems(data.approvals);}catch{}};load();const timer=setInterval(load,1500);return()=>{alive=false;clearInterval(timer);};},[taskId]);
 const decide=async(id,decision)=>{setBusy(id);setError('');try{const r=await fetch(`/api/tasks/${taskId}/approvals/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});const data=await r.json();if(!r.ok)throw new Error(data.error);setItems(values=>values.map(x=>x._id===id?data.approval:x));onChanged?.();}catch(e){setError(e.message);}finally{setBusy('');}};
 const pending=items.filter(x=>x.status==='pending');if(!pending.length&&!error)return null;
 return <div className="my-3 space-y-3">{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}{pending.map(item=><div key={item._id} className="rounded-xl border border-amber-300 bg-amber-50 dark:bg-amber-950/20 p-4"><p className="font-medium text-sm">需要你确认：{item.tool}</p><p className="mt-1 text-xs text-slate-500">允许后执行一次，5 分钟内有效。</p>{item.arguments.reviewFile&&<a href={item.arguments.reviewFile.url} className="mt-3 inline-block text-sm text-blue-600 underline" download={item.arguments.reviewFile.name}>审阅待提交文件：{item.arguments.reviewFile.name}（{Math.ceil(item.arguments.reviewFile.size/1024)} KB）</a>}<pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(item.arguments,null,2)}</pre><div className="mt-3 flex gap-2"><button disabled={busy===item._id} onClick={()=>decide(item._id,'approved')} className="rounded-lg bg-slate-900 dark:bg-slate-100 dark:text-slate-900 text-white px-4 py-2 text-sm">允许这一次</button><button disabled={busy===item._id} onClick={()=>decide(item._id,'rejected')} className="rounded-lg border border-slate-300 px-4 py-2 text-sm">拒绝</button></div></div>)}</div>;
}
